name: Node.js CI

on:
  push:
    branches:
      - main
      - Release
      - develop
  pull_request:
    branches:
      - main
      - Release
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
