name: Trigger Render Deployment
on:
  push:
    branches:
      - Release
jobs:
  main:
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: Trigger deployment
        uses: sws2apps/render-deployment@main #consider using pin for dependabot auto update
        with:
          serviceId: ea8034eac1488cfe725376103276c2ae
          apiKey: rnd_qUYG4w7FxEENVbxNiRLajK4eottJ
          multipleDeployment: false #optional, default true
